Repository eclipse/golo-lang, pull requests merged in 2020-10, with the labels that each got.

#554 📝 add first tutorial: building golo
  tutorials/README.md
  tutorials/build-golo.md
  tutorials/resources/build-golo/cloud-init.yaml
  tutorials/resources/build-golo/create-vm.sh
Labels: documentation

#555 📝 how to start quickly with Golo
  tutorials/README.md
  tutorials/first-steps.md
  tutorials/resources/first-steps/01-hello.golo
  tutorials/resources/first-steps/02-variables-and-co.golo
  tutorials/resources/first-steps/03-functions.golo
  tutorials/resources/first-steps/04-closures.golo
  tutorials/resources/first-steps/05-control-flow.golo
  tutorials/resources/first-steps/06-exceptions.golo
  tutorials/resources/first-steps/07-java-types.golo
  tutorials/resources/first-steps/08-modules.golo
  tutorials/resources/first-steps/my-tools.golo
Labels: documentation

#558 Fix nested try
  src/main/java/gololang/ir/Block.java
  src/main/java/gololang/ir/TryCatchFinally.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java
  src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
  src/test/resources/for-execution/nested-try.golo
Labels: bug, ready-for-review

#559 Adds man pages for the golo commands
  build.gradle.kts
  doc/basics.adoc
  doc/documenting.adoc
  doc/golo-guide.adoc
  doc/index.adoc
  doc/macros.adoc
  doc/man/man1/golo-check.adoc
  doc/man/man1/golo-compile.adoc
  doc/man/man1/golo-debug.adoc
  doc/man/man1/golo-diagnose.adoc
  doc/man/man1/golo-doc.adoc
  doc/man/man1/golo-golo.adoc
  doc/man/man1/golo-new.adoc
  doc/man/man1/golo-run.adoc
  doc/man/man1/golo-shebang.adoc
  doc/man/man1/golo.adoc
  doc/man/man1/golosh.adoc
  doc/man/man1/man-footer.adoc
  doc/man/man1/vanilla-golo.adoc
  doc/new-project.adoc
  src/main/java/org/eclipse/golo/cli/command/VersionCommand.java
  src/main/resources/commands.properties
Labels: documentation

#560 Improvements/misc
  doc/basics.adoc
  src/main/golo/functions.golo
  src/main/golo/gololang/macros/Utils.golo
  src/main/golo/lazylists.golo
  src/main/golo/standard-augmentations.golo
  src/main/java/gololang/HeadTail.java
  src/main/java/gololang/IO.java
  src/main/java/gololang/Predefined.java
  src/main/java/org/eclipse/golo/compiler/PackageAndClass.java
  src/main/java/org/eclipse/golo/runtime/ArrayHelper.java
  src/main/java/org/eclipse/golo/runtime/ArrayMethodFinder.java
  src/test/java/gololang/IOTest.java
  src/test/java/gololang/StandardAugmentationsTest.java
  src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
  src/test/resources/for-execution/arrays.golo
  src/test/resources/for-macros/asExpression.golo
  src/test/resources/for-test/bootstrapped-standard-augmentations.golo
  src/test/resources/for-test/macro-utils.golo
Labels: feature

#551 Adds Java annotation to golo elements
  src/main/golo/decorators.golo
  src/main/golo/gololang/macros.golo
  src/main/golo/gololang/macros/Utils.golo
  src/main/golo/gololang/meta/Annotations.golo
  src/main/golo/gololang/meta/README.md
  src/main/java/gololang/DynamicObject.java
  src/main/java/gololang/ir/ClassReference.java
  src/main/java/gololang/ir/CollectionLiteral.java
  src/main/java/gololang/ir/ToplevelElements.java
  src/main/java/gololang/ir/Visitors.java
  src/main/java/org/eclipse/golo/cli/command/ClasspathOption.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeStructGenerator.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeUnionGenerator.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java
  src/main/java/org/eclipse/golo/compiler/ParseTreeToGoloIrVisitor.java
  src/main/java/org/eclipse/golo/runtime/TypeMatching.java
  src/main/resources/messages.properties
  src/main/resources/messages_fr_FR.properties
  src/test/java/golo/test/annotations/Complex.java
  src/test/java/golo/test/annotations/OnAll.java
  src/test/java/golo/test/annotations/OnBoth.java
  src/test/java/golo/test/annotations/OnClass.java
  src/test/java/golo/test/annotations/OnClassInherit.java
  src/test/java/golo/test/annotations/OnMethod.java
  src/test/java/golo/test/annotations/Values.java
  src/test/java/golo/test/annotations/WithArrayArg.java
  src/test/java/golo/test/annotations/WithEnumArg.java
  src/test/java/golo/test/annotations/WithIntArg.java
  src/test/java/golo/test/annotations/WithNamedArg.java
  src/test/java/gololang/meta/AnnotationsTest.java
  src/test/java/org/eclipse/golo/compiler/MacroTest.java
  src/test/resources/for-macros/Annotate.golo
  src/test/resources/for-macros/annotation-macros.golo
  src/test/resources/for-macros/annotation.golo
  src/test/resources/for-test/macro-utils.golo
  src/test/resources/for-test/result.golo
Labels: feature, ready-for-review

#562 Use a fancy test logger
  build.gradle.kts
Labels: improvement, ready-for-review

#561 Reimplementing destructuring
  doc/basics.adoc
  src/main/golo/gololang/macros.golo
  src/main/golo/gololang/meta/Annotations.golo
  src/main/golo/standard-augmentations.golo
  src/main/java/gololang/AbstractRange.java
  src/main/java/gololang/BigIntegerRange.java
  src/main/java/gololang/CharRange.java
  src/main/java/gololang/GoloStruct.java
  src/main/java/gololang/HeadTail.java
  src/main/java/gololang/IntRange.java
  src/main/java/gololang/LazyList.java
  src/main/java/gololang/LongRange.java
  src/main/java/gololang/Range.java
  src/main/java/gololang/Tuple.java
  src/main/java/gololang/Union.java
  src/main/java/gololang/error/Result.java
  src/main/java/gololang/ir/BinaryOperation.java
  src/main/java/gololang/ir/FunctionContainer.java
  src/main/java/gololang/ir/NamedArgument.java
  src/main/java/gololang/ir/WhenClause.java
  src/main/java/org/eclipse/golo/compiler/SugarExpansionVisitor.java
  src/main/java/org/eclipse/golo/runtime/ArrayHelper.java
  src/main/java/org/eclipse/golo/runtime/ArrayMethodFinder.java
  src/main/java/org/eclipse/golo/runtime/InvalidDestructuringException.java
  src/main/resources/messages.properties
  src/main/resources/messages_fr_FR.properties
  src/test/java/gololang/LazyListTest.java
  src/test/java/gololang/error/ResultTest.java
  src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
  src/test/resources/for-execution/destruct-old.golo
  src/test/resources/for-execution/destruct.golo
  src/test/resources/for-test/lazylist.golo
  src/test/resources/for-test/macro-utils.golo
Labels: feature, improvement, ready-for-review

#566 Reworked Dockerfile
  Dockerfile
Labels: improvement

#565 README and CONTRIBUTING files cleanup
  CONTRIBUTING.md
  README.md
Labels: documentation

#564 Automated deployment
  .build/deploy.sh
  .build/golo-dev-sign.asc.gpg
  .build/gradle.properties.gpg
  .github/workflows/continuous-integration-and-deployment.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
Labels: improvement

#567 Sort compiling files
  src/main/java/gololang/EvaluationEnvironment.java
  src/main/java/gololang/Runtime.java
  src/main/java/gololang/error/Result.java
  src/main/java/gololang/ir/GoloModule.java
  src/main/java/org/eclipse/golo/cli/GoloFilesManager.java
  src/main/java/org/eclipse/golo/cli/Main.java
  src/main/java/org/eclipse/golo/cli/command/CheckCommand.java
  src/main/java/org/eclipse/golo/cli/command/ClasspathOption.java
  src/main/java/org/eclipse/golo/cli/command/CompilerCommand.java
  src/main/java/org/eclipse/golo/cli/command/DiagnoseCommand.java
  src/main/java/org/eclipse/golo/cli/command/DocCommand.java
  src/main/java/org/eclipse/golo/cli/command/GoloGoloCommand.java
  src/main/java/org/eclipse/golo/cli/command/InitCommand.java
  src/main/java/org/eclipse/golo/cli/command/Profile.java
  src/main/java/org/eclipse/golo/cli/command/RunCommand.java
  src/main/java/org/eclipse/golo/cli/command/ShebangCommand.java
  src/main/java/org/eclipse/golo/cli/command/VersionCommand.java
  src/main/java/org/eclipse/golo/cli/command/spi/CliCommand.java
  src/main/java/org/eclipse/golo/compiler/CodeGenerationResult.java
  src/main/java/org/eclipse/golo/compiler/GoloClassLoader.java
  src/main/java/org/eclipse/golo/compiler/GoloCompiler.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeStructGenerator.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeUnionGenerator.java
  src/main/java/org/eclipse/golo/compiler/PackageAndClass.java
  src/main/java/org/eclipse/golo/compiler/macro/MacroExpansionIrVisitor.java
  src/main/java/org/eclipse/golo/doc/ModuleDocumentation.java
  src/main/resources/commands.properties
  src/main/resources/commands_fr_FR.properties
  src/test/java/org/eclipse/golo/compiler/CompilationTest.java
  src/test/java/org/eclipse/golo/compiler/CompilerTest.java
  src/test/java/org/eclipse/golo/compiler/GoloClassLoaderTest.java
  src/test/java/org/eclipse/golo/doc/DocumentationRenderingTest.java
  src/test/java/org/eclipse/golo/doc/ModuleDocumentationTest.java
  src/test/java/org/eclipse/golo/internal/testing/TestUtils.java
Labels: improvement
