Repository eclipse/golo-lang, pull requests merged in 2020-11, with the labels that each got.

#556 📝 add 2 new tutorials: 🙀 OMG there is no class in Golo
  tutorials/README.md
  tutorials/dynamicobjects.md
  tutorials/resources/dynamicobjects/01-dynamicobjects-fields.golo
  tutorials/resources/dynamicobjects/02-dynamicobjects-methods.golo
  tutorials/resources/dynamicobjects/03-dynamicobjects-constructors.golo
  tutorials/resources/structures/01-structures.golo
  tutorials/resources/structures/02-structures-augmentations.golo
  tutorials/resources/structures/03-structures-named-augmentations.golo
  tutorials/structures.md
Labels: documentation, ready-for-review

#570 Refactor bytecode generation
  src/main/java/gololang/ir/FunctionInvocation.java
  src/main/java/gololang/ir/GoloFunction.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
Labels: ready-for-review

#569 FIX: return in try skips finally
  src/main/java/gololang/ir/Block.java
  src/main/java/gololang/ir/LocalReference.java
  src/main/java/gololang/ir/TryCatchFinally.java
  src/main/java/org/eclipse/golo/compiler/ClosureCaptureGoloIrVisitor.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeGenerationGoloIrVisitor.java
  src/main/java/org/eclipse/golo/compiler/JavaBytecodeUtils.java
  src/main/java/org/eclipse/golo/compiler/LocalReferenceAssignmentAndVerificationVisitor.java
  src/main/java/org/eclipse/golo/compiler/SugarExpansionVisitor.java
  src/test/java/org/eclipse/golo/compiler/CompileAndRunTest.java
  src/test/resources/for-execution/return-in-try.golo
Labels: bug, ready-for-review

#573 Add GitPod support
  .gitpod.Dockerfile
  .gitpod.yml
Labels: feature, improvement, tooling
